[build.environment]
HUGO_BASEURL = "https://techobyte.cc"
HUGO_VERSION = "0.152.2"
HUGO_ENV = "production"
NODE_VERSION = "22"
HUGO_ENABLEGITINFO = "true"

[build]
command = "hugo --gc --minify"
publish = "public"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
